name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Build Unit of work nuget via docker and publish
      uses: docker/build-push-action@v2
      with:
        context: /Source/Packages/UoW
        push: false
        tags: nugetbuild:latest
        build-args: NUGET_KEY=${{secrets.NUGET_API_KEY}}